---
threexui_enabled: true

threexui_data_directory: "{{ docker_home }}/3x-ui"
threexui_docker_image: ghcr.io/mhsanaei/3x-ui:latest

threexui_panel_subdomain: "3x"
threexui_subscription_subdomain: "3xsub"

threexui_reality_domain: "learn.microsoft.com"

threexui_vmess_aead_forced: "false"
threexui_enable_fail2ban: "true"
