---
- name: Warn about data directory cleaning
  ansible.builtin.debug:
    msg: "WARNING: 'obsidian_livesync_clean_datadir' is true. The existing Obsidian LiveSync data directory will be completely removed."
  when: obsidian_livesync_clean_datadir | default(false)

- name: Remove Obsidian LiveSync data directory if requested
  ansible.builtin.file:
    path: "{{ obsidian_livesync_data_directory }}"
    state: absent
  when: obsidian_livesync_clean_datadir | default(false)

- name: Create Obsidian LiveSync Directories
  ansible.builtin.file:
    path: "{{ obsidian_livesync_data_directory }}"
    state: directory

- name: Obsidian LiveSync Docker Container
  community.docker.docker_container:
    name: obsidian-livesync
    image: "{{ obsidian_livesync_image }}"
    pull: true
    recreate: true
    volumes:
      - "{{ obsidian_livesync_data_directory }}:/opt/couchdb/data"
    env:
      SERVER_URL: "https://{{ obsidian_livesync_subdomain }}.{{ server_hostname }}"
      COUCHDB_USER: "{{ obsidian_livesync_couchdb_user }}"
      COUCHDB_PASSWORD: "{{ obsidian_livesync_couchdb_password }}"
      COUCHDB_DATABASE: "{{ obsidian_livesync_couchdb_database }}"
    restart_policy: unless-stopped
    memory: "{{ obsidian_livesync_memory_limit }}"
    labels:
      traefik.enable: "{{ obsidian_livesync_available_externally }}"
      traefik.http.routers.obsidian_livesync.rule: "Host(`{{ obsidian_livesync_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.obsidian_livesync.loadbalancer.server.port: "5984"
      traefik.http.routers.obsidian_livesync.middlewares: "secure-headers@file"
  notify:
    - Pause for a few seconds to allow CouchDB to initialize
    - Create required CouchDB databases
