---
proxy_enabled: true
proxy_image: ghcr.io/senseunit/dumbproxy:latest

proxy_subdomain: "p"
proxy_user: "proxyuser"
proxy_user_password: "secret"

proxy_data_directory: "{{ docker_home }}/dumbproxy"
proxy_memory: 2g
