---
##
## User settings
##
admin_username: change_this
admin_userpassword: change_this
admin_userldappassword: change_this
admin_email: change_this@gmail.com

root_userpassword: change_this

lldap_base_dn: "dc=mayurifag,dc=local"
lldap_observer_user_password: "change_this_observer_password"

admin_authorized_keys: ""

server_timezone: Etc/UTC
server_hostname: mayurifag.local
server_ssh_port: 2222
swap_file_size_mb: "1024"
swap_swappiness: "15"

traefik_dns_provider: cloudflare
traefik_environment_variables:
  CF_DNS_API_TOKEN: "change_this"
# requests a wildcard certificate for your domain, so there should be no reason to have to use the staging
# letsencrypt acme server. If you do want to flip between staging/production, you might need to stop Traefik and clear
# the "{{ docker_home }}/traefik" after changing this setting.
traefik_acme_server: "https://acme-staging-v02.api.letsencrypt.org/directory" # staging
# traefik_acme_server: "https://acme-v02.api.letsencrypt.org/directory" # production

###
### General
###
ansible_python_interpreter: /usr/bin/python3

docker_home: /home/{{ admin_username }}/docker_data
files_home: /home/{{ admin_username }}/Files

# Traefik Directories (Shared with CrowdSec)
traefik_data_directory: "{{ docker_home }}/traefik"
traefik_logs_directory: "{{ traefik_data_directory }}/logs"
traefik_dynamic_configs_directory: "{{ traefik_data_directory }}/dynamic_configs"

##
## Galaxy extensions
##
docker_users:
  - "{{ admin_username }}"

docker_daemon_options:
  log-driver: "local"
  log-opts:
    max-size: "100m"

##################################

swap_enabled: true
mayurifag_github_io_enabled: true
lazydocker_enabled: true
docker_enabled: true

crowdsec_enabled: true
crowdsec_enroll_key: "change_me"

proxy_enabled: true
proxy_user: change_this
proxy_user_password: change_this
proxy_socks_port: "1080"
proxy_http_port: "1081"

mus_enabled: true
mus_subdomain: "mus"
mus_music_directory: "/home/{{ admin_username }}/music_folder/"

portainer_enabled: true
portainer_subdomain: "portainer"

traefik_enabled: true
traefik_subdomain: "traefik"

homepage_enabled: true
homepage_subdomain: "home"

gitea_enabled: true
gitea_subdomain: "git"
gitea_admin_password: "change_this"

watchtower_enabled: true
watchtower_subdomain: "watchtower"
watchtower_http_api_token: change_this

tinyauth_enabled: true
tinyauth_subdomain: "auth"

lldap_enabled: true
lldap_subdomain: "ldap"
lldap_jwt_secret: "change_this_random_string_min_32_chars"
lldap_key_seed: "change_this_random_string_min_32_chars"

threexui_enabled: true
threexui_panel_subdomain: "3x"

opencloud_enabled: true
opencloud_subdomain: "cloud"

bentopdf_enabled: true
bentopdf_subdomain: "pdf"

convertx_enabled: true
convertx_subdomain: "convert"

mini_qr_enabled: true
mini_qr_subdomain: "qr"

linkding_enabled: true
linkding_subdomain: "bookmarks"

glances_enabled: true
glances_subdomain: "glances"
glances_password: "change_this_glances_password"
