---
crowdsec_enabled: true

crowdsec_directory: "{{ docker_home }}/crowdsec"
crowdsec_data_directory: "{{ crowdsec_directory }}/data"
crowdsec_config_directory: "{{ crowdsec_directory }}/config"

crowdsec_image: crowdsecurity/crowdsec:latest

# Ban duration (1 week)
crowdsec_ban_duration: "168h"

# CrowdSec Console Enrollment
crowdsec_enroll_key: "change_me"
crowdsec_instance_name: "{{ server_hostname }}"

crowdsec_collections:
  - crowdsecurity/traefik
  - crowdsecurity/http-cve
  - crowdsecurity/base-http-scenarios
  - crowdsecurity/sshd
  - crowdsecurity/linux
  - crowdsecurity/appsec-generic-rules
  - crowdsecurity/appsec-virtual-patching
  - crowdsecurity/appsec-crs
