---
- name: Remove Linkding Data Directory
  ansible.builtin.file:
    path: "{{ linkding_data_directory }}"
    state: absent

- name: Create Linkding Data Directory
  ansible.builtin.file:
    path: "{{ linkding_data_directory }}"
    state: directory
    mode: "0755"
    owner: "1000"
    group: "1000"

- name: Linkding Docker Container
  community.docker.docker_container:
    name: linkding
    image: "{{ linkding_image }}"
    pull: true
    recreate: true
    restart_policy: unless-stopped
    memory: "{{ linkding_memory }}"
    volumes:
      - "{{ linkding_data_directory }}:/etc/linkding/data"
    env:
      LD_SUPERUSER_NAME: "{{ admin_username }}"
      LD_SUPERUSER_PASSWORD: "{{ admin_userldappassword }}"
      LD_CSRF_TRUSTED_ORIGINS: "https://{{ linkding_subdomain }}.{{ server_hostname }}"
    networks:
      - name: "web"
    labels:
      traefik.enable: "true"
      traefik.http.routers.linkding.rule: "Host(`{{ linkding_subdomain }}.{{ server_hostname }}`)"
      traefik.http.services.linkding.loadbalancer.server.port: "9090"

      # Replaces secure-headers@file to fix Referrer-Policy causing Origin: null (same-origin needed)
      traefik.http.middlewares.linkding-headers.headers.stsSeconds: "31536000"
      traefik.http.middlewares.linkding-headers.headers.stsIncludeSubdomains: "true"
      traefik.http.middlewares.linkding-headers.headers.stsPreload: "true"
      traefik.http.middlewares.linkding-headers.headers.forceSTSHeader: "true"
      traefik.http.middlewares.linkding-headers.headers.contentTypeNosniff: "true"
      traefik.http.middlewares.linkding-headers.headers.browserXssFilter: "true"
      traefik.http.middlewares.linkding-headers.headers.referrerPolicy: "same-origin"
      # throw https and domain
      traefik.http.middlewares.linkding-headers.headers.customrequestheaders.X-Forwarded-Proto: "https"
      traefik.http.middlewares.linkding-headers.headers.customrequestheaders.X-Forwarded-Host: "{{ linkding_subdomain }}.{{ server_hostname }}"

      traefik.http.routers.linkding.middlewares: "linkding-headers"

      com.centurylinklabs.watchtower.enable: "true"

      homepage.group: "Services"
      homepage.name: "Linkding"
      homepage.icon: "linkding.png"
      homepage.href: "https://{{ linkding_subdomain }}.{{ server_hostname }}"
