---
obsidian_livesync_enabled: true
obsidian_livesync_available_externally: "true"

obsidian_livesync_subdomain: "couchdbobsidian"

# Data directory
obsidian_livesync_data_directory: "{{ docker_home }}/obsidian_livesync"

# Set to true to wipe the data directory on deployment.
# WARNING: This will delete all your Obsidian LiveSync data.
obsidian_livesync_clean_datadir: false

# Docker image
obsidian_livesync_image: "oleduc/docker-obsidian-livesync-couchdb:master"

# Container memory limit
obsidian_livesync_memory_limit: "1g"

# CouchDB configuration
obsidian_livesync_couchdb_user: "obsidian_user"
obsidian_livesync_couchdb_password: "change_this"
obsidian_livesync_couchdb_database: "obsidian"
